[platformio]
default_envs = nodemcuv2
src_dir = .          ; ← Quelldateien liegen im Root, nicht in src/

[env_base]
platform  = espressif8266
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 80000000L
; LittleFS
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6

[env:nodemcuv2]
extends = env_base
board   = nodemcuv2

[env:d1_mini]
extends = env_base
board   = d1_mini

[env:esp12e]
extends = env_base
board   = esp12e
