[platformio]
default_envs = nodemcuv2

; ── Gemeinsame Einstellungen ──────────────────────────
[env_base]
platform  = espressif8266
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 80000000L
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6
    ESP8266WiFi
    ESP8266WebServer
    ESP8266HTTPUpdateServer
    LittleFS(esp8266)

; ── NodeMCU v2 (Standard) ────────────────────────────
[env:nodemcuv2]
extends = env_base
board   = nodemcuv2

; ── Wemos D1 Mini ────────────────────────────────────
[env:d1_mini]
extends = env_base
board   = d1_mini

; ── ESP-12E/F generisch ──────────────────────────────
[env:esp12e]
extends = env_base
board   = esp12e
